In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import datetime
# from datetime import datetime

In [2]:
df = pd.read_csv("C:\\Users\\OvaizAli\\Desktop\\FYP-2021\\FYP-I\\Master\\Data Collection\\CollectedData\\Final_Data (2022).csv", index_col = False)

In [3]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [119]:
df.head(7)

Province Country_Region        Date  Day  Month  Year  \
0             Balochistan       Pakistan  2020-03-10   10      3  2020   
1               Islamabad       Pakistan  2020-03-10   10      3  2020   
2                  Punjab       Pakistan  2020-03-10   10      3  2020   
3                   Sindh       Pakistan  2020-03-10   10      3  2020   
4      Khyber Pakhtunkhwa       Pakistan  2020-03-10   10      3  2020   
5  Azad Jammu and Kashmir       Pakistan  2020-03-10   10      3  2020   
6        Gilgit-Baltistan       Pakistan  2020-03-10   10      3  2020   

         Lat      Long_  Confirmed  Deaths  ...  admis_upper_vax  \
0  28.328492  65.898403        1.0     0.0  ...              0.0   
1  33.665087  73.121219        2.0     0.0  ...              0.0   
2  30.811346  72.139132        0.0     0.0  ...              0.0   
3  26.009446  68.776807        0.0     0.0  ...              0.0   
4  34.485332  72.091690        0.0     0.0  ...              0.0   
5  34.027401  73.947253        0.0     0.0  ...              0.0   
6  35.792146  74.982138        2.0     0.0  ...              0.0   

   admis_lower_vax  admis_mean_unvax  admis_upper_unvax  admis_lower_unvax  \
0              0.0         25.615120           44.61881          10.791250   
1              0.0          0.004133            0.00000           0.000000   
2              0.0         40.904370           89.53674          11.384460   
3              0.0         22.339800           81.02134           6.179772   
4              0.0         17.376130           39.58196           5.953569   
5              0.0          0.000000            0.00000           0.000000   
6              0.0         12.495310           23.41426           3.297438   

    Temp   Wind  Barometer  Visibility  Weather  
0  46.29  15.00      31.43        0.00    Haze.  
1  65.14   9.57      34.71       21.33   Clear.  
2  56.40   2.44      23.67       11.88   Clear.  
3  65.14   9.57      34.71       21.33   Clear.  
4  48.80   4.64      49.20       23.21     Fog.  
5  39.86   1.86      42.43        0.00   Clear.  
6  32.71   3.71      23.57       12.82     Fog.  

[7 rows x 74 columns]

In [56]:
df.columns

Index(['Province', 'Country_Region', 'Date', 'Day', 'Month', 'Year', 'Lat',
       'Long_', 'Confirmed', 'Deaths', 'Daily_Confirmed', 'Recovered',
       'Daily_Deaths', 'inf_mean', 'inf_upper', 'inf_lower',
       'seir_cumulative_mean', 'seir_cumulative_lower',
       'seir_cumulative_upper', 'inf_cuml_mean', 'inf_cuml_lower',
       'inf_cuml_upper', 'seir_daily_mean', 'seir_daily_lower',
       'seir_daily_upper', 'seir_daily_unscaled_mean',
       'seir_daily_unscaled_lower', 'seir_daily_unscaled_upper',
       'seir_cumulative_unscaled_mean', 'seir_cumulative_unscaled_lower',
       'seir_cumulative_unscaled_upper', 'cases_mean', 'cases_lower',
       'cases_upper', 'inf_cuml_mean_vax', 'inf_cuml_lower_vax',
       'inf_cuml_upper_vax', 'inf_cuml_mean_unvax', 'inf_cuml_lower_unvax',
       'inf_cuml_upper_unvax', 'inf_mean_vax', 'inf_lower_vax',
       'inf_upper_vax', 'inf_mean_unvax', 'inf_lower_unvax', 'inf_upper_unvax',
       'population', 'mobility_mean', 'mobility_obs', 't

# Tensors for Confirmed Cases

In [57]:
sConfirmed = df[df['Province'] == 'Sindh']['Daily_Confirmed'].values
bConfirmed = df[df['Province'] == 'Balochistan']['Daily_Confirmed'].values
gConfirmed = df[df['Province'] == 'Gilgit-Baltistan']['Daily_Confirmed'].values
iConfirmed = df[df['Province'] == 'Islamabad']['Daily_Confirmed'].values
pConfirmed = df[df['Province'] == 'Punjab']['Daily_Confirmed'].values
kConfirmed = df[df['Province'] == 'Khyber Pakhtunkhwa']['Daily_Confirmed'].values
aConfirmed = df[df['Province'] == 'Azad Jammu and Kashmir']['Daily_Confirmed'].values

In [58]:
len(sConfirmed) == len(bConfirmed) == len(iConfirmed) == len(pConfirmed) == len(kConfirmed) == len(aConfirmed) == len(gConfirmed)

True

In [59]:
sbConfirmed = np.zeros(len(sConfirmed)*2)
giConfirmed = np.zeros(len(sConfirmed)*2)
pkConfirmed = np.zeros(len(sConfirmed)*2)
axConfirmed = np.zeros(len(sConfirmed)*2)

In [60]:
len(sbConfirmed)
# S B
# G I
# P K
# A -

1406

In [61]:
for i in range(0, len(sConfirmed), 2):
    sbConfirmed[i] = sConfirmed[i]
    sbConfirmed[i+1] = bConfirmed[i]

In [62]:
for i in range(0, len(sConfirmed), 2):
    giConfirmed[i] = gConfirmed[i]
    giConfirmed[i+1] = iConfirmed[i]

In [63]:
for i in range(0, len(sConfirmed), 2):
    pkConfirmed[i] = pConfirmed[i]
    pkConfirmed[i+1] = kConfirmed[i]

In [64]:
for i in range(0, len(sConfirmed), 2):
    axConfirmed[i] = aConfirmed[i]
    axConfirmed[i+1] = -1

In [65]:
AllConfirmed = np.zeros((4, len(sConfirmed)*2))

In [66]:
AllConfirmed[0] = sbConfirmed
AllConfirmed[1] = giConfirmed
AllConfirmed[2] = pkConfirmed
AllConfirmed[3] = axConfirmed

In [67]:
# AllConfirmed[0]

In [68]:
# AllConfirmed

In [69]:
# AllConfirmed[0][:8]

In [70]:
# len(sbConfirmed)/8

In [71]:
tempArr = np.zeros((4, 8))

In [72]:
tensorsArr = np.zeros((88, 4, 8))

In [73]:
# tensorsArr[43]

In [74]:
stIndex = 0
enIndex = 8
for tIndex in range(88):
    for i in range(4):
        tempArr[i] = AllConfirmed[i][stIndex:enIndex]
    stIndex += 8
    enIndex += 8
    tensorsArr[tIndex] = tempArr

In [244]:
len(tensorsArr[0])

4

In [75]:
finalTensorsArr = np.zeros((44, 8, 8))

In [76]:
# finalTensorsArr[0]

In [77]:
# tensorsArr[0]

In [78]:
stIndex = 0
enIndex = 8
for tIndex in range(0, 88, 2):
    tfIndex = tIndex//2
    for i in range(8):
        if(i < 4):
#             print(tensors[tIndex][i])
            finalTensorsArr[tfIndex][i] = tensorsArr[tIndex][i]
#             print(FinalTensors[tfIndex][i])
        else:
#             print(tensors[tIndex][i-4])
            finalTensorsArr[tfIndex][i] = tensorsArr[tIndex][i-4]
#             print(FinalTensors[tfIndex][i-4])
#     print(FinalTensors[tfIndex])
#     print("\n")

In [79]:
# print(finalTensorsArr[0])

In [80]:
confirmedTensors = [] 

In [81]:
for i in range(44):
    confirmedTensors.append(tf.convert_to_tensor(finalTensorsArr[i], dtype=tf.float64))

In [82]:
confirmedTensors[0]

<tf.Tensor: shape=(8, 8), dtype=float64, numpy=
array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 2.,  2.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 0., -1.,  0., -1.,  0., -1.,  0., -1.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 2.,  2.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 0., -1.,  0., -1.,  0., -1.,  0., -1.]])>

In [215]:
len(confirmedTensors) * 8

352

In [111]:
y_tempConfirmed = []

In [112]:
x = 0
for i in range(0, len(df['Date']), 7):
    try:
        y_tempConfirmed.append(df[df['Date'] == str(datetime.datetime.strptime(df['Date'].iloc[i], '%Y-%m-%d') + datetime.timedelta(days=8))[:10]]['Daily_Confirmed'].values)
#         for data in df[(df['Date'] == str(datetime.datetime.strptime(df['Date'].iloc[i], '%Y-%m-%d') + datetime.timedelta(days=8))[:10])]['Daily_Confirmed']:
#             print(data)
#         print(df[
#         (df['Date'] == str(datetime.datetime.strptime(df['Date'].iloc[i], '%Y-%m-%d') + datetime.timedelta(days=8))[:10])
#     & (df['Province'] == 'Sindh')]['Daily_Confirmed'].values[0])
    except:
        continue

In [263]:
y_tempConfirmed = y_tempConfirmed[:695]

In [264]:
# Balochistan
# Islamabad
# Punjab
# Sindh
# Khyber Pakhtunkhwa
# Azad Jammu and Kashmir
# Gilgit-Baltistan

In [265]:
bCases = []
iCases = []
pCases = []
sCases = []
kCases = []
aCases = []
gCases = []

In [267]:
for i in range(len(y_tempConfirmed)):
    try:
        bCases.append(y_tempConfirmed[i][0])
        iCases.append(y_tempConfirmed[i][1])
        pCases.append(y_tempConfirmed[i][2])
        sCases.append(y_tempConfirmed[i][3])
        kCases.append(y_tempConfirmed[i][4])
        aCases.append(y_tempConfirmed[i][5])
        gCases.append(y_tempConfirmed[i][6])
    except:
        continue

In [268]:
bSumCases = np.zeros(87)
iSumCases = np.zeros(87)
pSumCases = np.zeros(87)
sSumCases = np.zeros(87)
kSumCases = np.zeros(87)
aSumCases = np.zeros(87)
gSumCases = np.zeros(87)

In [269]:
for i in range(0, len(bCases), 8):    
    try:
        for j in range(8):
            if (i > 0):
                bSumCases[int(i/8)] += bCases[i+j]
                iSumCases[int(i/8)] += iCases[i+j]
                pSumCases[int(i/8)] += pCases[i+j]
                sSumCases[int(i/8)] += sCases[i+j]
                kSumCases[int(i/8)] += kCases[i+j]
                aSumCases[int(i/8)] += aCases[i+j]
                gSumCases[int(i/8)] += gCases[i+j]
            else:
                bSumCases[int(i)] += bCases[i+j]
                iSumCases[int(i)] += iCases[i+j]
                pSumCases[int(i)] += pCases[i+j]
                sSumCases[int(i)] += sCases[i+j]
                kSumCases[int(i)] += kCases[i+j]
                aSumCases[int(i)] += aCases[i+j]
                gSumCases[int(i)] += gCases[i+j]
    except:
        continue

In [273]:
bSumCases[86]

400.0

In [274]:
ySumConfirmed = np.zeros((86, 8, 1))

In [275]:
ySumConfirmed[0]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [276]:
for i in range(86):
    ySumConfirmed[i][0] = bSumCases[i] 
    ySumConfirmed[i][1] = iSumCases[i]  
    ySumConfirmed[i][2] = pSumCases[i] 
    ySumConfirmed[i][3] = sSumCases[i]  
    ySumConfirmed[i][4] = kSumCases[i] 
    ySumConfirmed[i][5] = aSumCases[i] 
    ySumConfirmed[i][6] = gSumCases[i] 
    ySumConfirmed[i][7] = -1

In [277]:
len(ySumConfirmed)

86

In [280]:
ySumConfirmed[85]

array([[ 5.2500e+02],
       [ 8.9450e+03],
       [ 1.6081e+04],
       [ 1.5133e+04],
       [ 1.1400e+04],
       [ 3.5890e+03],
       [ 2.4200e+02],
       [-1.0000e+00]])

In [281]:
yConfirmedTensors = []

In [282]:
for i in range(86):
    yConfirmedTensors.append(tf.convert_to_tensor(ySumConfirmed[i], dtype=tf.float64))

In [290]:
X = confirmedTensors
y = yConfirmedTensors[:44]

In [291]:
len(X)

44

In [292]:
len(y)

44