# Importing Necessary Libraries

In [171]:
import pandas as pd
import numpy as np
import tensorflow as tf
import datetime
from numpy import expand_dims
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D,Activation,Dropout

# Loading Dataset

In [172]:
df = pd.read_csv("C:\\Users\\OvaizAli\\Desktop\\FYP-2021\\FYP-I\\Master\\Data Collection\\CollectedData\\Final_Data (2022).csv", index_col = False)

In [173]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [174]:
df.head(7)

Province Country_Region        Date  Day  Month  Year  \
0             Balochistan       Pakistan  2020-03-10   10      3  2020   
1               Islamabad       Pakistan  2020-03-10   10      3  2020   
2                  Punjab       Pakistan  2020-03-10   10      3  2020   
3                   Sindh       Pakistan  2020-03-10   10      3  2020   
4      Khyber Pakhtunkhwa       Pakistan  2020-03-10   10      3  2020   
5  Azad Jammu and Kashmir       Pakistan  2020-03-10   10      3  2020   
6        Gilgit-Baltistan       Pakistan  2020-03-10   10      3  2020   

         Lat      Long_  Confirmed  Deaths  ...  admis_upper_vax  \
0  28.328492  65.898403        1.0     0.0  ...              0.0   
1  33.665087  73.121219        2.0     0.0  ...              0.0   
2  30.811346  72.139132        0.0     0.0  ...              0.0   
3  26.009446  68.776807        0.0     0.0  ...              0.0   
4  34.485332  72.091690        0.0     0.0  ...              0.0   
5  34.027401  73.947253        0.0     0.0  ...              0.0   
6  35.792146  74.982138        2.0     0.0  ...              0.0   

   admis_lower_vax  admis_mean_unvax  admis_upper_unvax  admis_lower_unvax  \
0              0.0         25.615120           44.61881          10.791250   
1              0.0          0.004133            0.00000           0.000000   
2              0.0         40.904370           89.53674          11.384460   
3              0.0         22.339800           81.02134           6.179772   
4              0.0         17.376130           39.58196           5.953569   
5              0.0          0.000000            0.00000           0.000000   
6              0.0         12.495310           23.41426           3.297438   

    Temp   Wind  Barometer  Visibility  Weather  
0  46.29  15.00      31.43        0.00    Haze.  
1  65.14   9.57      34.71       21.33   Clear.  
2  56.40   2.44      23.67       11.88   Clear.  
3  65.14   9.57      34.71       21.33   Clear.  
4  48.80   4.64      49.20       23.21     Fog.  
5  39.86   1.86      42.43        0.00   Clear.  
6  32.71   3.71      23.57       12.82     Fog.  

[7 rows x 74 columns]

# Creating Tensors for Confirmed Cases

### Generating "X" from Tabular Data

In [175]:
sConfirmed = df[df['Province'] == 'Sindh']['Daily_Confirmed'].values
bConfirmed = df[df['Province'] == 'Balochistan']['Daily_Confirmed'].values
gConfirmed = df[df['Province'] == 'Gilgit-Baltistan']['Daily_Confirmed'].values
iConfirmed = df[df['Province'] == 'Islamabad']['Daily_Confirmed'].values
pConfirmed = df[df['Province'] == 'Punjab']['Daily_Confirmed'].values
kConfirmed = df[df['Province'] == 'Khyber Pakhtunkhwa']['Daily_Confirmed'].values
aConfirmed = df[df['Province'] == 'Azad Jammu and Kashmir']['Daily_Confirmed'].values

In [176]:
len(sConfirmed) == len(bConfirmed) == len(iConfirmed) == len(pConfirmed) == len(kConfirmed) == len(aConfirmed) == len(gConfirmed)

True

In [177]:
sbConfirmed = np.zeros(len(sConfirmed)*2)
giConfirmed = np.zeros(len(sConfirmed)*2)
pkConfirmed = np.zeros(len(sConfirmed)*2)
axConfirmed = np.zeros(len(sConfirmed)*2)

In [178]:
len(sbConfirmed)
# S B
# G I
# P K
# A -

1406

In [179]:
for i in range(0, len(sConfirmed), 2):
    sbConfirmed[i] = sConfirmed[i]
    sbConfirmed[i+1] = bConfirmed[i]

In [180]:
for i in range(0, len(sConfirmed), 2):
    giConfirmed[i] = gConfirmed[i]
    giConfirmed[i+1] = iConfirmed[i]

In [181]:
for i in range(0, len(sConfirmed), 2):
    pkConfirmed[i] = pConfirmed[i]
    pkConfirmed[i+1] = kConfirmed[i]

In [182]:
for i in range(0, len(sConfirmed), 2):
    axConfirmed[i] = aConfirmed[i]
    axConfirmed[i+1] = -1

In [183]:
AllConfirmed = np.zeros((4, len(sConfirmed)*2))

In [184]:
AllConfirmed[0] = sbConfirmed
AllConfirmed[1] = giConfirmed
AllConfirmed[2] = pkConfirmed
AllConfirmed[3] = axConfirmed

In [189]:
tempArr = np.zeros((4, 8))

In [190]:
tensorsArr = np.zeros((88, 4, 8))

In [191]:
stIndex = 0
enIndex = 8
for tIndex in range(88):
    for i in range(4):
        tempArr[i] = AllConfirmed[i][stIndex:enIndex]
    stIndex += 8
    enIndex += 8
    tensorsArr[tIndex] = tempArr

In [192]:
len(tensorsArr[0])

4

In [193]:
tensorsArr[0]

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 2.,  2.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 0., -1.,  0., -1.,  0., -1.,  0., -1.]])

In [194]:
finalTensorsArr = np.zeros((44, 8, 8))

In [167]:
stIndex = 0
enIndex = 8
for tIndex in range(0, 88, 2):
    tfIndex = tIndex//2
    for i in range(8):
        if(i < 4):
#             print(tensors[tIndex][i])
            finalTensorsArr[tfIndex][i] = tensorsArr[tIndex][i]
#             print(FinalTensors[tfIndex][i])
        else:
#             print(tensors[tIndex][i-4])
            finalTensorsArr[tfIndex][i] = tensorsArr[tIndex][i-4]
#             print(FinalTensors[tfIndex][i-4])
#     print(FinalTensors[tfIndex])
#     print("\n")

In [168]:
confirmedTensors = []

In [169]:
for i in range(44):
    confirmedTensors.append(tf.convert_to_tensor(finalTensorsArr[i], dtype=tf.float64))

In [170]:
confirmedTensors[0]

<tf.Tensor: shape=(8, 8), dtype=float64, numpy=
array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 2.,  2.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 0., -1.,  0., -1.,  0., -1.,  0., -1.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 2.,  2.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.],
       [ 0., -1.,  0., -1.,  0., -1.,  0., -1.]])>

In [37]:
len(confirmedTensors) * 8

352

### Generating "y" from Tabular Data

In [38]:
y_tempConfirmed = []

In [39]:
x = 0
for i in range(0, len(df['Date']), 7):
    try:
        y_tempConfirmed.append(df[df['Date'] == str(datetime.datetime.strptime(df['Date'].iloc[i], '%Y-%m-%d') + datetime.timedelta(days=7))[:10]]['Daily_Confirmed'].values)
#         for data in df[(df['Date'] == str(datetime.datetime.strptime(df['Date'].iloc[i], '%Y-%m-%d') + datetime.timedelta(days=8))[:10])]['Daily_Confirmed']:
#             print(data)
#         print(df[
#         (df['Date'] == str(datetime.datetime.strptime(df['Date'].iloc[i], '%Y-%m-%d') + datetime.timedelta(days=8))[:10])
#     & (df['Province'] == 'Sindh')]['Daily_Confirmed'].values[0])
    except:
        continue

In [40]:
y_tempConfirmed[0]

array([ 1.,  1., 25.,  0.,  2.,  0.,  0.])

In [41]:
y_tempConfirmed = y_tempConfirmed[:696]

In [42]:
# Balochistan
# Islamabad
# Punjab
# Sindh
# Khyber Pakhtunkhwa
# Azad Jammu and Kashmir
# Gilgit-Baltistan

In [43]:
bCases = []
iCases = []
pCases = []
sCases = []
kCases = []
aCases = []
gCases = []

In [44]:
for i in range(len(y_tempConfirmed)):
    try:
        bCases.append(y_tempConfirmed[i][0])
        iCases.append(y_tempConfirmed[i][1])
        pCases.append(y_tempConfirmed[i][2])
        sCases.append(y_tempConfirmed[i][3])
        kCases.append(y_tempConfirmed[i][4])
        aCases.append(y_tempConfirmed[i][5])
        gCases.append(y_tempConfirmed[i][6])
    except:
        continue

In [45]:
bSumCases = np.zeros(88)
iSumCases = np.zeros(88)
pSumCases = np.zeros(88)
sSumCases = np.zeros(88)
kSumCases = np.zeros(88)
aSumCases = np.zeros(88)
gSumCases = np.zeros(88)

In [46]:
for i in range(0, len(bCases), 7):    
    try:
        for j in range(7):
            if (i > 0):
                bSumCases[int(i/7)] += bCases[i+j]
                iSumCases[int(i/7)] += iCases[i+j]
                pSumCases[int(i/7)] += pCases[i+j]
                sSumCases[int(i/7)] += sCases[i+j]
                kSumCases[int(i/7)] += kCases[i+j]
                aSumCases[int(i/7)] += aCases[i+j]
                gSumCases[int(i/7)] += gCases[i+j]
            else:
                bSumCases[int(i)] += bCases[i+j]
                iSumCases[int(i)] += iCases[i+j]
                pSumCases[int(i)] += pCases[i+j]
                sSumCases[int(i)] += sCases[i+j]
                kSumCases[int(i)] += kCases[i+j]
                aSumCases[int(i)] += aCases[i+j]
                gSumCases[int(i)] += gCases[i+j]
    except:
        continue

In [115]:
ySumConfirmed = np.zeros((88, 7, 1))

In [116]:
ySumConfirmed[0]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [117]:
for i in range(88):
    ySumConfirmed[i][0] = bSumCases[i] 
    ySumConfirmed[i][1] = iSumCases[i]  
    ySumConfirmed[i][2] = pSumCases[i] 
    ySumConfirmed[i][3] = sSumCases[i]  
    ySumConfirmed[i][4] = kSumCases[i] 
    ySumConfirmed[i][5] = aSumCases[i] 
    ySumConfirmed[i][6] = gSumCases[i] 

In [118]:
len(ySumConfirmed)

88

In [119]:
ySumConfirmed[87]

array([[  44.],
       [ 144.],
       [ 576.],
       [1044.],
       [ 482.],
       [  24.],
       [   5.]])

In [121]:
yConfirmedTensors = np.zeros((88, 7, 1))

In [122]:
for i in range(88):
    yConfirmedTensors[i] = tf.convert_to_tensor(ySumConfirmed[i], dtype=tf.float64)

# Data Preparation

In [123]:
X = confirmedTensors
y = yConfirmedTensors[:44]

In [131]:
X = np.array(X)

In [132]:
X.shape

(44, 8, 8)

In [146]:
# Expanding the dimensions for the CNN
X = expand_dims(X, axis=3)

In [147]:
X.shape

(44, 8, 8, 1, 1)

In [134]:
y.shape

(44, 7, 1)

# Model Implementation for Predicting Confirmed Cases for each Province in next 7 days

In [137]:
model = Sequential()

model.add(Conv2D(64, (3, 3), input_shape=(8, 8, 1)))
model.add(Activation("relu"))
model.add(MaxPooling2D((2,2), padding='same'))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), input_shape=(8, 8, 1)))
model.add(Activation("relu"))
model.add(MaxPooling2D((2,2), padding='same'))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(36, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax'))

model.compile(loss=tf.keras.losses.MeanSquaredError(), optimizer='adam')

In [138]:
model.fit(X, y, batch_size = 32, epochs = 10, validation_split = 0.2)

Epoch 1/10
2/2 [==============================] - 6s 804ms/step - loss: 10738289.0000 - val_loss: 15774983.0000
Epoch 2/10
2/2 [==============================] - 0s 68ms/step - loss: 10738060.0000 - val_loss: 15774610.0000
Epoch 3/10
2/2 [==============================] - 0s 54ms/step - loss: 10738154.0000 - val_loss: 15774396.0000
Epoch 4/10
2/2 [==============================] - 0s 60ms/step - loss: 10738342.0000 - val_loss: 15774396.0000
Epoch 5/10
2/2 [==============================] - 0s 50ms/step - loss: 10738210.0000 - val_loss: 15774396.0000
Epoch 6/10
2/2 [==============================] - 0s 57ms/step - loss: 10738171.0000 - val_loss: 15774396.0000
Epoch 7/10
2/2 [==============================] - 0s 46ms/step - loss: 10738074.0000 - val_loss: 15774396.0000
Epoch 8/10
2/2 [==============================] - 0s 44ms/step - loss: 10737945.0000 - val_loss: 15774396.0000
Epoch 9/10
2/2 [==============================] - 0s 40ms/step - loss: 10737940.0000 - val_loss: 15774396.0000
