In [33]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
df = pd.read_csv("C:\\Users\\OvaizAli\\Desktop\\FYP-2021\\FYP-I\\Master\\Data Collection\\CollectedData\\Final_Data (2022).csv", index_col = False)

In [3]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [4]:
df.head(7)

Province Country_Region        Date  Day  Month  Year  \
0             Balochistan       Pakistan  2020-03-10   10      3  2020   
1               Islamabad       Pakistan  2020-03-10   10      3  2020   
2                  Punjab       Pakistan  2020-03-10   10      3  2020   
3                   Sindh       Pakistan  2020-03-10   10      3  2020   
4      Khyber Pakhtunkhwa       Pakistan  2020-03-10   10      3  2020   
5  Azad Jammu and Kashmir       Pakistan  2020-03-10   10      3  2020   
6        Gilgit-Baltistan       Pakistan  2020-03-10   10      3  2020   

         Lat      Long_  Confirmed  Deaths  ...  admis_upper_vax  \
0  28.328492  65.898403        1.0     0.0  ...              0.0   
1  33.665087  73.121219        2.0     0.0  ...              0.0   
2  30.811346  72.139132        0.0     0.0  ...              0.0   
3  26.009446  68.776807        0.0     0.0  ...              0.0   
4  34.485332  72.091690        0.0     0.0  ...              0.0   
5  34.027401  73.947253        0.0     0.0  ...              0.0   
6  35.792146  74.982138        2.0     0.0  ...              0.0   

   admis_lower_vax  admis_mean_unvax  admis_upper_unvax  admis_lower_unvax  \
0              0.0         25.615120           44.61881          10.791250   
1              0.0          0.004133            0.00000           0.000000   
2              0.0         40.904370           89.53674          11.384460   
3              0.0         22.339800           81.02134           6.179772   
4              0.0         17.376130           39.58196           5.953569   
5              0.0          0.000000            0.00000           0.000000   
6              0.0         12.495310           23.41426           3.297438   

    Temp   Wind  Barometer  Visibility  Weather  
0  46.29  15.00      31.43        0.00    Haze.  
1  65.14   9.57      34.71       21.33   Clear.  
2  56.40   2.44      23.67       11.88   Clear.  
3  65.14   9.57      34.71       21.33   Clear.  
4  48.80   4.64      49.20       23.21     Fog.  
5  39.86   1.86      42.43        0.00   Clear.  
6  32.71   3.71      23.57       12.82     Fog.  

[7 rows x 74 columns]

# Tensors for Confirmed Cases

In [5]:
sConfirmed = df[df['Province'] == 'Sindh']['Confirmed'].values
bConfirmed = df[df['Province'] == 'Balochistan']['Confirmed'].values
gConfirmed = df[df['Province'] == 'Gilgit-Baltistan']['Confirmed'].values
iConfirmed = df[df['Province'] == 'Islamabad']['Confirmed'].values
pConfirmed = df[df['Province'] == 'Punjab']['Confirmed'].values
kConfirmed = df[df['Province'] == 'Khyber Pakhtunkhwa']['Confirmed'].values
aConfirmed = df[df['Province'] == 'Azad Jammu and Kashmir']['Confirmed'].values

In [6]:
len(sConfirmed) == len(bConfirmed) == len(iConfirmed) == len(pConfirmed) == len(kConfirmed) == len(aConfirmed) == len(gConfirmed)

True

In [7]:
sbConfirmed = np.zeros(len(sConfirmed)*2)
giConfirmed = np.zeros(len(sConfirmed)*2)
pkConfirmed = np.zeros(len(sConfirmed)*2)
axConfirmed = np.zeros(len(sConfirmed)*2)

In [8]:
len(sbConfirmed)
# S B
# G I
# P K
# A -

1406

In [9]:
for i in range(0, len(sConfirmed), 2):
    sbConfirmed[i] = sConfirmed[i]
    sbConfirmed[i+1] = bConfirmed[i]

In [10]:
for i in range(0, len(sConfirmed), 2):
    giConfirmed[i] = gConfirmed[i]
    giConfirmed[i+1] = iConfirmed[i]

In [11]:
for i in range(0, len(sConfirmed), 2):
    pkConfirmed[i] = pConfirmed[i]
    pkConfirmed[i+1] = kConfirmed[i]

In [12]:
for i in range(0, len(sConfirmed), 2):
    axConfirmed[i] = aConfirmed[i]
    axConfirmed[i+1] = np.nan

In [13]:
AllConfirmed = np.zeros((4, len(sConfirmed)*2))

In [14]:
AllConfirmed[0] = sbConfirmed
AllConfirmed[1] = giConfirmed
AllConfirmed[2] = pkConfirmed
AllConfirmed[3] = axConfirmed

In [15]:
AllConfirmed[0]

array([0., 1., 0., ..., 0., 0., 0.])

In [16]:
AllConfirmed

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 2.,  2.,  3., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., nan,  0., ...,  0.,  0.,  0.]])

In [17]:
AllConfirmed[0][:8]

array([ 0.,  1.,  0.,  1.,  0.,  6.,  0., 14.])

In [18]:
len(sbConfirmed)/8

175.75

In [19]:
tempArr = np.zeros((4, 8))

In [20]:
tensorsArr = np.zeros((88, 4, 8))

In [21]:
tensorsArr[43]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
stIndex = 0
enIndex = 8
for tIndex in range(88):
    for i in range(4):
        tempArr[i] = AllConfirmed[i][stIndex:enIndex]
    stIndex += 8
    enIndex += 8
    tensorsArr[tIndex] = tempArr

In [23]:
finalTensorsArr = np.zeros((44, 8, 8))

In [24]:
finalTensorsArr[0]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
tensorsArr[0]

array([[ 0.,  1.,  0.,  1.,  0.,  6.,  0., 14.],
       [ 2.,  2.,  3.,  2.,  3.,  4.,  3.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., 15.],
       [ 0., nan,  0., nan,  0., nan,  0., nan]])

In [26]:
stIndex = 0
enIndex = 8
for tIndex in range(0, 88, 2):
    tfIndex = tIndex//2
    for i in range(8):
        if(i < 4):
#             print(tensors[tIndex][i])
            finalTensorsArr[tfIndex][i] = tensorsArr[tIndex][i]
#             print(FinalTensors[tfIndex][i])
        else:
#             print(tensors[tIndex][i-4])
            finalTensorsArr[tfIndex][i] = tensorsArr[tIndex][i-4]
#             print(FinalTensors[tfIndex][i-4])
#     print(FinalTensors[tfIndex])
#     print("\n")

In [35]:
print(finalTensorsArr[0])

[[ 0.  1.  0.  1.  0.  6.  0. 14.]
 [ 2.  2.  3.  2.  3.  4.  3.  4.]
 [ 0.  0.  0.  0.  0.  0.  1. 15.]
 [ 0. nan  0. nan  0. nan  0. nan]
 [ 0.  1.  0.  1.  0.  6.  0. 14.]
 [ 2.  2.  3.  2.  3.  4.  3.  4.]
 [ 0.  0.  0.  0.  0.  0.  1. 15.]
 [ 0. nan  0. nan  0. nan  0. nan]]


In [39]:
confirmedTensors = [] 

In [42]:
for i in range(44):
    confirmedTensors.append(tf.convert_to_tensor(finalTensorsArr[i], dtype=tf.float64))

In [46]:
confirmedTensors[0]

<tf.Tensor: shape=(8, 8), dtype=float64, numpy=
array([[ 0.,  1.,  0.,  1.,  0.,  6.,  0., 14.],
       [ 2.,  2.,  3.,  2.,  3.,  4.,  3.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., 15.],
       [ 0., nan,  0., nan,  0., nan,  0., nan],
       [ 0.,  1.,  0.,  1.,  0.,  6.,  0., 14.],
       [ 2.,  2.,  3.,  2.,  3.,  4.,  3.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., 15.],
       [ 0., nan,  0., nan,  0., nan,  0., nan]])>